name: Terraform Plan

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6  # pon aquí la versión que usas en local

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

